name: Build and test

on:
  push:
    branches-ignore:
      - main

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: 23

      - name: Install dependencies
        run: npm install

  lint:
    runs-on: ubuntu-latest
    needs: checkout
    continue-on-error: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: 23

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

  outdated:
    runs-on: ubuntu-latest
    needs: checkout
    continue-on-error: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: 23

      - name: Install dependencies
        run: npm install

      - name: Check for outdated dependencies
        run: npm outdated

  test:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: 23

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
        env:
          CI: true

  build:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: 23

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build